### ISSUE TITLE
Toggles don't reflect true state of features upon app launch

### ISSUE THREAD

**Issue by PeterTheSalmon** [tkgka/Switcher#3]
Small bug with the new update.

When launching the app both toggles will maintain their previous state. However, these states aren't reflected in the experience.

For example, with both disabled:
![Screen Shot 2022-02-01 at 7 53 45 AM](https://user-images.githubusercontent.com/87033324/152002531-7c650789-507d-4462-afc8-86e20116b8f3.png)

You would expect both the CMD-Q and mouse wheel direction to not work. However, they are both enabled until the toggles are switched.

This occurs whenever the app is launched, regardless of toggle state. Both will be enabled.

Thanks!

**Comment by tkgka** [comment]
bug fixed on version 1.0.8h
thank you for the report :)
