### ISSUE TITLE
App didn't open

### ISSUE THREAD

**Issue by laazybeard** [tkgka/Switcher#8]
After installation and granted permission nothings happened when I run app. Running on macOS 12.3.1, MBP with Intel.

**Comment by tkgka** [comment]
can you move the Application to the Applications folder and try again?

**Comment by laazybeard** [comment]
With pleasure but its already here. I tried to open it from dmg too. Also try previous version with same result.

**Comment by tkgka** [comment]
oh... ok I'll check it out asap

**Comment by laazybeard** [comment]
thanks!

**Comment by tkgka** [comment]
@laazybeard does app opens on v2.0.2?

I fixed some code and it works fine on my Mac now

**Comment by laazybeard** [comment]
> @laazybeard does app opens on v2.0.2?
> 
> I fixed some code and it works fine on my Mac now

Now it works! 👍
